### ISSUE TITLE
Seems Broken

### ISSUE THREAD

**Issue by FOSSFOREVER** [halukilhan/uys#20]
Greetings, I've noticed this script has been broken. I really love this script and have tried to fix it myself but am not very good at javascript. If you find time to look at it I would really appreciate it. Youtube should have this layout by default!

**Comment by lleaff** [comment]
Not the creator or anything but it would help if you described the issue a bit more precisely, I could help fix specific issues.

**Comment by FOSSFOREVER** [comment]
Ah crap I guess that would help. Give me a few hours here, currently getting off work. Will update the best I can with what I have. Thanks!

**Comment by lleaff** [comment]
I made some basic fixes for the HTML5 player mode ([pull request](https://github.com/halukilhan/uys/pull/21)), I can't test with the Flash player so I don't know if that is still broken or not.
