### ISSUE TITLE
Anyone want to carry the torch?

### ISSUE THREAD

**Issue by FOSSFOREVER** [halukilhan/uys#22]
I loved this script for a while but it has been broken for far too long due to youtube's ever changing code. Anyone willing to work on the issues to get this functionality restored? I would if I could, I've been tampering a little but am out of my element here.

I'm working with latest Firefox. Currently utilizing other scripts but haven't been able to come close to this type of function.

**Comment by Recchan** [comment]
Most of the functions are working in mine at least. All I need to do is get the player to update its position every time the sidebar pops out. I'm definitely not confident enough to carry the torch.
